/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PayrollSoftwareRouteImport } from './routes/payroll-software'
import { Route as PayrollForStartupsRouteImport } from './routes/payroll-for-startups'
import { Route as PayrollForSmesRouteImport } from './routes/payroll-for-smes'
import { Route as PayrollForSchoolsRouteImport } from './routes/payroll-for-schools'
import { Route as PayrollForRetailRouteImport } from './routes/payroll-for-retail'
import { Route as PayrollForRestaurantsRouteImport } from './routes/payroll-for-restaurants'
import { Route as PayrollForManufacturingRouteImport } from './routes/payroll-for-manufacturing'
import { Route as PayrollForLogisticsRouteImport } from './routes/payroll-for-logistics'
import { Route as PayrollForHotelsRouteImport } from './routes/payroll-for-hotels'
import { Route as PayrollForHealthcareRouteImport } from './routes/payroll-for-healthcare'
import { Route as LeaveManagementRouteImport } from './routes/leave-management'
import { Route as HrmsSoftwareRouteImport } from './routes/hrms-software'
import { Route as GshrmVsZohoPayrollRouteImport } from './routes/gshrm-vs-zoho-payroll'
import { Route as GshrmVsRazorpayPayrollRouteImport } from './routes/gshrm-vs-razorpay-payroll'
import { Route as GshrmVsPetpoojaRouteImport } from './routes/gshrm-vs-petpooja'
import { Route as GshrmVsPagarbookRouteImport } from './routes/gshrm-vs-pagarbook'
import { Route as GshrmVsKekaRouteImport } from './routes/gshrm-vs-keka'
import { Route as GshrmVsGreythrRouteImport } from './routes/gshrm-vs-greythr'
import { Route as EmployeeSelfServiceRouteImport } from './routes/employee-self-service'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as ComplianceManagementRouteImport } from './routes/compliance-management'
import { Route as BookDemoRouteImport } from './routes/book-demo'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AttendanceManagementRouteImport } from './routes/attendance-management'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollSoftwareRoute = PayrollSoftwareRouteImport.update({
  id: '/payroll-software',
  path: '/payroll-software',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForStartupsRoute = PayrollForStartupsRouteImport.update({
  id: '/payroll-for-startups',
  path: '/payroll-for-startups',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForSmesRoute = PayrollForSmesRouteImport.update({
  id: '/payroll-for-smes',
  path: '/payroll-for-smes',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForSchoolsRoute = PayrollForSchoolsRouteImport.update({
  id: '/payroll-for-schools',
  path: '/payroll-for-schools',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForRetailRoute = PayrollForRetailRouteImport.update({
  id: '/payroll-for-retail',
  path: '/payroll-for-retail',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForRestaurantsRoute = PayrollForRestaurantsRouteImport.update({
  id: '/payroll-for-restaurants',
  path: '/payroll-for-restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForManufacturingRoute = PayrollForManufacturingRouteImport.update({
  id: '/payroll-for-manufacturing',
  path: '/payroll-for-manufacturing',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForLogisticsRoute = PayrollForLogisticsRouteImport.update({
  id: '/payroll-for-logistics',
  path: '/payroll-for-logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForHotelsRoute = PayrollForHotelsRouteImport.update({
  id: '/payroll-for-hotels',
  path: '/payroll-for-hotels',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollForHealthcareRoute = PayrollForHealthcareRouteImport.update({
  id: '/payroll-for-healthcare',
  path: '/payroll-for-healthcare',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaveManagementRoute = LeaveManagementRouteImport.update({
  id: '/leave-management',
  path: '/leave-management',
  getParentRoute: () => rootRouteImport,
} as any)
const HrmsSoftwareRoute = HrmsSoftwareRouteImport.update({
  id: '/hrms-software',
  path: '/hrms-software',
  getParentRoute: () => rootRouteImport,
} as any)
const GshrmVsZohoPayrollRoute = GshrmVsZohoPayrollRouteImport.update({
  id: '/gshrm-vs-zoho-payroll',
  path: '/gshrm-vs-zoho-payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const GshrmVsRazorpayPayrollRoute = GshrmVsRazorpayPayrollRouteImport.update({
  id: '/gshrm-vs-razorpay-payroll',
  path: '/gshrm-vs-razorpay-payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const GshrmVsPetpoojaRoute = GshrmVsPetpoojaRouteImport.update({
  id: '/gshrm-vs-petpooja',
  path: '/gshrm-vs-petpooja',
  getParentRoute: () => rootRouteImport,
} as any)
const GshrmVsPagarbookRoute = GshrmVsPagarbookRouteImport.update({
  id: '/gshrm-vs-pagarbook',
  path: '/gshrm-vs-pagarbook',
  getParentRoute: () => rootRouteImport,
} as any)
const GshrmVsKekaRoute = GshrmVsKekaRouteImport.update({
  id: '/gshrm-vs-keka',
  path: '/gshrm-vs-keka',
  getParentRoute: () => rootRouteImport,
} as any)
const GshrmVsGreythrRoute = GshrmVsGreythrRouteImport.update({
  id: '/gshrm-vs-greythr',
  path: '/gshrm-vs-greythr',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeSelfServiceRoute = EmployeeSelfServiceRouteImport.update({
  id: '/employee-self-service',
  path: '/employee-self-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceManagementRoute = ComplianceManagementRouteImport.update({
  id: '/compliance-management',
  path: '/compliance-management',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDemoRoute = BookDemoRouteImport.update({
  id: '/book-demo',
  path: '/book-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceManagementRoute = AttendanceManagementRouteImport.update({
  id: '/attendance-management',
  path: '/attendance-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/compliance-management': typeof ComplianceManagementRoute
  '/contact-us': typeof ContactUsRoute
  '/employee-self-service': typeof EmployeeSelfServiceRoute
  '/gshrm-vs-greythr': typeof GshrmVsGreythrRoute
  '/gshrm-vs-keka': typeof GshrmVsKekaRoute
  '/gshrm-vs-pagarbook': typeof GshrmVsPagarbookRoute
  '/gshrm-vs-petpooja': typeof GshrmVsPetpoojaRoute
  '/gshrm-vs-razorpay-payroll': typeof GshrmVsRazorpayPayrollRoute
  '/gshrm-vs-zoho-payroll': typeof GshrmVsZohoPayrollRoute
  '/hrms-software': typeof HrmsSoftwareRoute
  '/leave-management': typeof LeaveManagementRoute
  '/payroll-for-healthcare': typeof PayrollForHealthcareRoute
  '/payroll-for-hotels': typeof PayrollForHotelsRoute
  '/payroll-for-logistics': typeof PayrollForLogisticsRoute
  '/payroll-for-manufacturing': typeof PayrollForManufacturingRoute
  '/payroll-for-restaurants': typeof PayrollForRestaurantsRoute
  '/payroll-for-retail': typeof PayrollForRetailRoute
  '/payroll-for-schools': typeof PayrollForSchoolsRoute
  '/payroll-for-smes': typeof PayrollForSmesRoute
  '/payroll-for-startups': typeof PayrollForStartupsRoute
  '/payroll-software': typeof PayrollSoftwareRoute
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/compliance-management': typeof ComplianceManagementRoute
  '/contact-us': typeof ContactUsRoute
  '/employee-self-service': typeof EmployeeSelfServiceRoute
  '/gshrm-vs-greythr': typeof GshrmVsGreythrRoute
  '/gshrm-vs-keka': typeof GshrmVsKekaRoute
  '/gshrm-vs-pagarbook': typeof GshrmVsPagarbookRoute
  '/gshrm-vs-petpooja': typeof GshrmVsPetpoojaRoute
  '/gshrm-vs-razorpay-payroll': typeof GshrmVsRazorpayPayrollRoute
  '/gshrm-vs-zoho-payroll': typeof GshrmVsZohoPayrollRoute
  '/hrms-software': typeof HrmsSoftwareRoute
  '/leave-management': typeof LeaveManagementRoute
  '/payroll-for-healthcare': typeof PayrollForHealthcareRoute
  '/payroll-for-hotels': typeof PayrollForHotelsRoute
  '/payroll-for-logistics': typeof PayrollForLogisticsRoute
  '/payroll-for-manufacturing': typeof PayrollForManufacturingRoute
  '/payroll-for-restaurants': typeof PayrollForRestaurantsRoute
  '/payroll-for-retail': typeof PayrollForRetailRoute
  '/payroll-for-schools': typeof PayrollForSchoolsRoute
  '/payroll-for-smes': typeof PayrollForSmesRoute
  '/payroll-for-startups': typeof PayrollForStartupsRoute
  '/payroll-software': typeof PayrollSoftwareRoute
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-us': typeof AboutUsRoute
  '/admin': typeof AdminRoute
  '/admin-login': typeof AdminLoginRoute
  '/attendance-management': typeof AttendanceManagementRoute
  '/blog': typeof BlogRouteWithChildren
  '/book-demo': typeof BookDemoRoute
  '/compliance-management': typeof ComplianceManagementRoute
  '/contact-us': typeof ContactUsRoute
  '/employee-self-service': typeof EmployeeSelfServiceRoute
  '/gshrm-vs-greythr': typeof GshrmVsGreythrRoute
  '/gshrm-vs-keka': typeof GshrmVsKekaRoute
  '/gshrm-vs-pagarbook': typeof GshrmVsPagarbookRoute
  '/gshrm-vs-petpooja': typeof GshrmVsPetpoojaRoute
  '/gshrm-vs-razorpay-payroll': typeof GshrmVsRazorpayPayrollRoute
  '/gshrm-vs-zoho-payroll': typeof GshrmVsZohoPayrollRoute
  '/hrms-software': typeof HrmsSoftwareRoute
  '/leave-management': typeof LeaveManagementRoute
  '/payroll-for-healthcare': typeof PayrollForHealthcareRoute
  '/payroll-for-hotels': typeof PayrollForHotelsRoute
  '/payroll-for-logistics': typeof PayrollForLogisticsRoute
  '/payroll-for-manufacturing': typeof PayrollForManufacturingRoute
  '/payroll-for-restaurants': typeof PayrollForRestaurantsRoute
  '/payroll-for-retail': typeof PayrollForRetailRoute
  '/payroll-for-schools': typeof PayrollForSchoolsRoute
  '/payroll-for-smes': typeof PayrollForSmesRoute
  '/payroll-for-startups': typeof PayrollForStartupsRoute
  '/payroll-software': typeof PayrollSoftwareRoute
  '/pricing': typeof PricingRoute
  '/blog/$slug': typeof BlogSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-us'
    | '/admin'
    | '/admin-login'
    | '/attendance-management'
    | '/blog'
    | '/book-demo'
    | '/compliance-management'
    | '/contact-us'
    | '/employee-self-service'
    | '/gshrm-vs-greythr'
    | '/gshrm-vs-keka'
    | '/gshrm-vs-pagarbook'
    | '/gshrm-vs-petpooja'
    | '/gshrm-vs-razorpay-payroll'
    | '/gshrm-vs-zoho-payroll'
    | '/hrms-software'
    | '/leave-management'
    | '/payroll-for-healthcare'
    | '/payroll-for-hotels'
    | '/payroll-for-logistics'
    | '/payroll-for-manufacturing'
    | '/payroll-for-restaurants'
    | '/payroll-for-retail'
    | '/payroll-for-schools'
    | '/payroll-for-smes'
    | '/payroll-for-startups'
    | '/payroll-software'
    | '/pricing'
    | '/blog/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-us'
    | '/admin'
    | '/admin-login'
    | '/attendance-management'
    | '/blog'
    | '/book-demo'
    | '/compliance-management'
    | '/contact-us'
    | '/employee-self-service'
    | '/gshrm-vs-greythr'
    | '/gshrm-vs-keka'
    | '/gshrm-vs-pagarbook'
    | '/gshrm-vs-petpooja'
    | '/gshrm-vs-razorpay-payroll'
    | '/gshrm-vs-zoho-payroll'
    | '/hrms-software'
    | '/leave-management'
    | '/payroll-for-healthcare'
    | '/payroll-for-hotels'
    | '/payroll-for-logistics'
    | '/payroll-for-manufacturing'
    | '/payroll-for-restaurants'
    | '/payroll-for-retail'
    | '/payroll-for-schools'
    | '/payroll-for-smes'
    | '/payroll-for-startups'
    | '/payroll-software'
    | '/pricing'
    | '/blog/$slug'
  id:
    | '__root__'
    | '/'
    | '/about-us'
    | '/admin'
    | '/admin-login'
    | '/attendance-management'
    | '/blog'
    | '/book-demo'
    | '/compliance-management'
    | '/contact-us'
    | '/employee-self-service'
    | '/gshrm-vs-greythr'
    | '/gshrm-vs-keka'
    | '/gshrm-vs-pagarbook'
    | '/gshrm-vs-petpooja'
    | '/gshrm-vs-razorpay-payroll'
    | '/gshrm-vs-zoho-payroll'
    | '/hrms-software'
    | '/leave-management'
    | '/payroll-for-healthcare'
    | '/payroll-for-hotels'
    | '/payroll-for-logistics'
    | '/payroll-for-manufacturing'
    | '/payroll-for-restaurants'
    | '/payroll-for-retail'
    | '/payroll-for-schools'
    | '/payroll-for-smes'
    | '/payroll-for-startups'
    | '/payroll-software'
    | '/pricing'
    | '/blog/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutUsRoute: typeof AboutUsRoute
  AdminRoute: typeof AdminRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AttendanceManagementRoute: typeof AttendanceManagementRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookDemoRoute: typeof BookDemoRoute
  ComplianceManagementRoute: typeof ComplianceManagementRoute
  ContactUsRoute: typeof ContactUsRoute
  EmployeeSelfServiceRoute: typeof EmployeeSelfServiceRoute
  GshrmVsGreythrRoute: typeof GshrmVsGreythrRoute
  GshrmVsKekaRoute: typeof GshrmVsKekaRoute
  GshrmVsPagarbookRoute: typeof GshrmVsPagarbookRoute
  GshrmVsPetpoojaRoute: typeof GshrmVsPetpoojaRoute
  GshrmVsRazorpayPayrollRoute: typeof GshrmVsRazorpayPayrollRoute
  GshrmVsZohoPayrollRoute: typeof GshrmVsZohoPayrollRoute
  HrmsSoftwareRoute: typeof HrmsSoftwareRoute
  LeaveManagementRoute: typeof LeaveManagementRoute
  PayrollForHealthcareRoute: typeof PayrollForHealthcareRoute
  PayrollForHotelsRoute: typeof PayrollForHotelsRoute
  PayrollForLogisticsRoute: typeof PayrollForLogisticsRoute
  PayrollForManufacturingRoute: typeof PayrollForManufacturingRoute
  PayrollForRestaurantsRoute: typeof PayrollForRestaurantsRoute
  PayrollForRetailRoute: typeof PayrollForRetailRoute
  PayrollForSchoolsRoute: typeof PayrollForSchoolsRoute
  PayrollForSmesRoute: typeof PayrollForSmesRoute
  PayrollForStartupsRoute: typeof PayrollForStartupsRoute
  PayrollSoftwareRoute: typeof PayrollSoftwareRoute
  PricingRoute: typeof PricingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-software': {
      id: '/payroll-software'
      path: '/payroll-software'
      fullPath: '/payroll-software'
      preLoaderRoute: typeof PayrollSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-startups': {
      id: '/payroll-for-startups'
      path: '/payroll-for-startups'
      fullPath: '/payroll-for-startups'
      preLoaderRoute: typeof PayrollForStartupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-smes': {
      id: '/payroll-for-smes'
      path: '/payroll-for-smes'
      fullPath: '/payroll-for-smes'
      preLoaderRoute: typeof PayrollForSmesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-schools': {
      id: '/payroll-for-schools'
      path: '/payroll-for-schools'
      fullPath: '/payroll-for-schools'
      preLoaderRoute: typeof PayrollForSchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-retail': {
      id: '/payroll-for-retail'
      path: '/payroll-for-retail'
      fullPath: '/payroll-for-retail'
      preLoaderRoute: typeof PayrollForRetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-restaurants': {
      id: '/payroll-for-restaurants'
      path: '/payroll-for-restaurants'
      fullPath: '/payroll-for-restaurants'
      preLoaderRoute: typeof PayrollForRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-manufacturing': {
      id: '/payroll-for-manufacturing'
      path: '/payroll-for-manufacturing'
      fullPath: '/payroll-for-manufacturing'
      preLoaderRoute: typeof PayrollForManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-logistics': {
      id: '/payroll-for-logistics'
      path: '/payroll-for-logistics'
      fullPath: '/payroll-for-logistics'
      preLoaderRoute: typeof PayrollForLogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-hotels': {
      id: '/payroll-for-hotels'
      path: '/payroll-for-hotels'
      fullPath: '/payroll-for-hotels'
      preLoaderRoute: typeof PayrollForHotelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll-for-healthcare': {
      id: '/payroll-for-healthcare'
      path: '/payroll-for-healthcare'
      fullPath: '/payroll-for-healthcare'
      preLoaderRoute: typeof PayrollForHealthcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leave-management': {
      id: '/leave-management'
      path: '/leave-management'
      fullPath: '/leave-management'
      preLoaderRoute: typeof LeaveManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hrms-software': {
      id: '/hrms-software'
      path: '/hrms-software'
      fullPath: '/hrms-software'
      preLoaderRoute: typeof HrmsSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gshrm-vs-zoho-payroll': {
      id: '/gshrm-vs-zoho-payroll'
      path: '/gshrm-vs-zoho-payroll'
      fullPath: '/gshrm-vs-zoho-payroll'
      preLoaderRoute: typeof GshrmVsZohoPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gshrm-vs-razorpay-payroll': {
      id: '/gshrm-vs-razorpay-payroll'
      path: '/gshrm-vs-razorpay-payroll'
      fullPath: '/gshrm-vs-razorpay-payroll'
      preLoaderRoute: typeof GshrmVsRazorpayPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gshrm-vs-petpooja': {
      id: '/gshrm-vs-petpooja'
      path: '/gshrm-vs-petpooja'
      fullPath: '/gshrm-vs-petpooja'
      preLoaderRoute: typeof GshrmVsPetpoojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gshrm-vs-pagarbook': {
      id: '/gshrm-vs-pagarbook'
      path: '/gshrm-vs-pagarbook'
      fullPath: '/gshrm-vs-pagarbook'
      preLoaderRoute: typeof GshrmVsPagarbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gshrm-vs-keka': {
      id: '/gshrm-vs-keka'
      path: '/gshrm-vs-keka'
      fullPath: '/gshrm-vs-keka'
      preLoaderRoute: typeof GshrmVsKekaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gshrm-vs-greythr': {
      id: '/gshrm-vs-greythr'
      path: '/gshrm-vs-greythr'
      fullPath: '/gshrm-vs-greythr'
      preLoaderRoute: typeof GshrmVsGreythrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee-self-service': {
      id: '/employee-self-service'
      path: '/employee-self-service'
      fullPath: '/employee-self-service'
      preLoaderRoute: typeof EmployeeSelfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance-management': {
      id: '/compliance-management'
      path: '/compliance-management'
      fullPath: '/compliance-management'
      preLoaderRoute: typeof ComplianceManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-demo': {
      id: '/book-demo'
      path: '/book-demo'
      fullPath: '/book-demo'
      preLoaderRoute: typeof BookDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance-management': {
      id: '/attendance-management'
      path: '/attendance-management'
      fullPath: '/attendance-management'
      preLoaderRoute: typeof AttendanceManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutUsRoute: AboutUsRoute,
  AdminRoute: AdminRoute,
  AdminLoginRoute: AdminLoginRoute,
  AttendanceManagementRoute: AttendanceManagementRoute,
  BlogRoute: BlogRouteWithChildren,
  BookDemoRoute: BookDemoRoute,
  ComplianceManagementRoute: ComplianceManagementRoute,
  ContactUsRoute: ContactUsRoute,
  EmployeeSelfServiceRoute: EmployeeSelfServiceRoute,
  GshrmVsGreythrRoute: GshrmVsGreythrRoute,
  GshrmVsKekaRoute: GshrmVsKekaRoute,
  GshrmVsPagarbookRoute: GshrmVsPagarbookRoute,
  GshrmVsPetpoojaRoute: GshrmVsPetpoojaRoute,
  GshrmVsRazorpayPayrollRoute: GshrmVsRazorpayPayrollRoute,
  GshrmVsZohoPayrollRoute: GshrmVsZohoPayrollRoute,
  HrmsSoftwareRoute: HrmsSoftwareRoute,
  LeaveManagementRoute: LeaveManagementRoute,
  PayrollForHealthcareRoute: PayrollForHealthcareRoute,
  PayrollForHotelsRoute: PayrollForHotelsRoute,
  PayrollForLogisticsRoute: PayrollForLogisticsRoute,
  PayrollForManufacturingRoute: PayrollForManufacturingRoute,
  PayrollForRestaurantsRoute: PayrollForRestaurantsRoute,
  PayrollForRetailRoute: PayrollForRetailRoute,
  PayrollForSchoolsRoute: PayrollForSchoolsRoute,
  PayrollForSmesRoute: PayrollForSmesRoute,
  PayrollForStartupsRoute: PayrollForStartupsRoute,
  PayrollSoftwareRoute: PayrollSoftwareRoute,
  PricingRoute: PricingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
